// src/App.tsx
import React, { useState } from 'react';
import { Sidebar } from './components/Sidebar';
import { Header } from './components/Header';
import { EmployeeList } from './components/EmployeeList';
import { employees } from './data/employees';
import { Filters } from './types/filters';
import { filterEmployees } from './utils/filterEmployees';

export default function App() {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedTeam, setSelectedTeam] = useState('');
  const [activeFilters, setActiveFilters] = useState<Filters>({
    department: '',
    experience: '',
    yearOfJoining: '',
    location: '',
    team: ''
  });

  const handleTeamChange = (team: string) => {
    setSelectedTeam(team);
    setActiveFilters(prev => ({ ...prev, team }));
  };

  const filteredEmployees = filterEmployees(employees, activeFilters).filter(emp =>
    emp.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    emp.email.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="flex min-h-screen bg-gray-100">
      <Sidebar onFilterChange={setActiveFilters} />
      <div className="flex-1 flex flex-col">
        <Header selectedTeam={selectedTeam} onTeamChange={handleTeamChange} />
        <EmployeeList
          employees={filteredEmployees}
          onEdit={() => {}}
          onDelete={() => {}}
          searchTerm={searchTerm}
          onSearchChange={setSearchTerm}
        />
      </div>
    </div>
  );
}

// src/app/app.component.ts
import { Component } from '@angular/core';
import { Employee } from './types/employee';
import { Filters } from './types/filters';
import { EmployeeService } from './services/employee.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  selectedTeam = '';
  searchTerm = '';
  activeFilters: Filters = {
    department: '',
    experience: '',
    yearOfJoining: '',
    location: '',
    team: ''
  };

  constructor(private employeeService: EmployeeService) {}

  get filteredEmployees(): Employee[] {
    return this.employeeService.filterEmployees(this.activeFilters, this.searchTerm);
  }

  onTeamChange(team: string): void {
    this.selectedTeam = team;
    this.activeFilters = { ...this.activeFilters, team };
  }

  onFilterChange(filters: Filters): void {
    this.activeFilters = filters;
  }

  onSearchChange(term: string): void {
    this.searchTerm = term;
  }
}
<div class="flex min-h-screen bg-gray-100">
  <app-sidebar (filterChange)="onFilterChange($event)"></app-sidebar>
  <div class="flex-1 flex flex-col">
    <app-header
      [selectedTeam]="selectedTeam"
      (teamChange)="onTeamChange($event)">
    </app-header>
    <app-employee-list
      [employees]="filteredEmployees"
      [searchTerm]="searchTerm"
      (searchChange)="onSearchChange($event)">
    </app-employee-list>
  </div>
</div>
